### ISSUE TITLE
Show * in Mandatory fields in Signup.

### ISSUE THREAD

**Issue by afrid1997** [zeon-hq/zeon#40]
I gave the Phone Number field EMpty. it was not proceeding.
Put Mandatory markers in the input fields for the Sign up form
<@U06ADS021AP> <@U066J9GE2FM>

[Slack Message](https://zeonhq-workspace.slack.com/archives/C06A4SGAH6C/p1705305257693209)

**Comment by kaushalendra-pandey** [comment]
Added error messages if the form is submitted without required fields. Same for login page as well
